# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d5161c7690423c097b9b6cd508acd56890153391cd6a7e2b9111afe56cebfeb79945fb84bc621a8b4dc81ca8472a1d010067e8d081efdb4fbe2b6c32966fb6

test:
  secret_key_base: 47a9a9dab22f0d9d28cfa7d8e0f10c59154031106b79ce92824de0c9af154a55060513bbb5670c754062e15ef722c9dda2d18dbfd0867e696df377b272aa7790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
